### ISSUE TITLE
Xây dựng test case và test cho các chức năng

### ISSUE THREAD

**Issue by Pau1901** [Group15-ServiceXuLyVaLuuTruVideo/Group15-ServiceXuLyVaLuuTruVideo#18]
- [x] 1. Xây dựng test case và test cho chức năng tạo project

- [x] 2. Xây dựng test case và test cho chức năng cắt nội dung video

- [x] 3. Xây dựng test case và test cho chức năng cắt khung ảnh video

- [x] 4. Xây dựng test case và test cho chức năng tải lên hình ảnh có sẳn để tạo preview thumbnail

- [x] 5. Xây dựng testcase và test cho chức năng lấy thông tin project cụ thể 

- [x] 6. Xây dựng testcase và test cho chức năng chuyển độ phân giải video

- [x] 7. Xây dựng testcase và test cho chức năng lấy video file
- [x] 8. Xây dựng testcase và tiến hành test cho chức năng liệt kê các project hiện có
- [x] 9. Xây dựng testcase và tiến hành test cho chức năng xóa project
- [x] 10. Xây dựng testcase và tiến hành test cho chức năng xoay video

**Comment by Pau1901** [comment]
1 - 7
Link doc: https://docs.google.com/document/d/1TXlnFQbhL-mevaHCTcjzvMyp73dDPgSUNZcDGq8ETgQ/edit?usp=sharing

**Comment by phucphuc02** [comment]
8-10
https://docs.google.com/document/d/1vw3_OTrUfA44C7EVqiHgwtn4qyRJ7IAhJ2bJHYjvCXo/edit?usp=sharing
