### ISSUE TITLE
Tìm hiểu đề tài

### ISSUE THREAD

**Issue by phucphuc02** [Group15-ServiceXuLyVaLuuTruVideo/Group15-ServiceXuLyVaLuuTruVideo#2]
- Tìm hiểu mục tiêu cần đạt được
- Phương pháp triển khai đề tài

**Comment by Pau1901** [comment]
1. Tạo một trình chỉnh chỉnh sửa video API Web HTTP thân thiện với kho lưu trữ tệp có thể cắm, phụ trợ chỉnh sửa video và khả năng phát trực tuyến.
2. Phương pháp triển khai:

- Về phần FrontEnd: chúng ta sẽ sử dụng ReactJs để phát triển phần giao diện cho người sử dụng với nhiều chức năng chỉnh sửa cắt ghép video API Web HTTP.
- Về phần BackEnd: chúng ta sử dụng công cụ chính là Python để phát triển phần xử lý các dữ liệu và các thao tác thuận tiện trên giao diện cho người dùng.
