### ISSUE TITLE
Setup Code

### ISSUE THREAD

**Issue by phucphuc02** [Group15-ServiceXuLyVaLuuTruVideo/Group15-ServiceXuLyVaLuuTruVideo#3]
- FE: Reactjs
- BE: Python

**Comment by Pau1901** [comment]
[Task 2.docx](https://github.com/Group15-ServiceXuLyVaLuuTruVideo/Group15-ServiceXuLyVaLuuTruVideo/files/11019852/Task.2.docx)

**Comment by Pau1901** [comment]
[Task 2.docx](https://github.com/Group15-ServiceXuLyVaLuuTruVideo/Group15-ServiceXuLyVaLuuTruVideo/files/11019864/Task.2.docx)
