### ISSUE TITLE
100% code được vẽ class diagram

### ISSUE THREAD

**Issue by phucphuc02** [Group15-ServiceXuLyVaLuuTruVideo/Group15-ServiceXuLyVaLuuTruVideo#5]
1. Xác định các class
2. Vẽ class diagram

**Comment by Pau1901** [comment]
video-server
├── src
│   ├── videoserver
│   │   ├── apps
│   │   │   ├── projects                    (chứa các file routes, task)
│   │   │   ├── swagger
|   │   │   │   └── static                    (chứa các file liên quan đến ui của swagger)
|   │   │   │   └── templates            (chứa file index.html của swagger)
│   │   ├── lib
│   │   │   ├── storage                    (lưu trữ file system)
│   │   │   ├── video_editor            (chứa cái file liên quan đến việc thực hiện edit video sử dụng ffmpeg)
│   │   │   │   └── script               
├── tests
│   ├── api                                      (chứa các api để test việc thêm, sửa, xóa video và thumbnail)
│   ├── storage
│   |   └── fixtures                           (chứa hình ảnh và video dùng để test)
|   ├── video                                   (chứa file test các chức năng của thư viện ffmpeg)

**Comment by phucphuc02** [comment]
https://docs.google.com/document/d/1ty84HQC9GyMs5usAA4hJW9AGETyzEYWPDlURZeLs-R8/edit?usp=sharing
